// frontend/src/Components/Login/Login.jsx
import React, { useState } from "react";
import "./login.css";
import axios from "axios";
import { useSelector, useDispatch } from "react-redux";
import { setToken, setUser } from "../../redux/slices/authSlice";
import { useNavigate } from "react-router-dom";

//imgs
import loginImg from "../../assets/images/bgs/login.png";

const Login = () => {
  const [userMail, setUserMail] = useState("");
  const [userPassword, setUserPassword] = useState("");

  const apiUrl = import.meta.env.VITE_API_URL;
  const token = useSelector((state) => state.auth.token);
  const dispatch = useDispatch();
  const navigate = useNavigate();

  const onSubmitHandler = async (e) => {
    e.preventDefault();
    try {
      const params = new URLSearchParams();
      params.append("username", userMail);
      params.append("password", userPassword);
      const response = await axios.post(`${apiUrl}/login`, params);
      const token = response.data.access_token;
      if (token) {
        const user = await axios.post(`${apiUrl}/test-token`, null, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });
        dispatch(setToken(token));
        dispatch(setUser(user.data));
        console.log("auth success", response.data);
        if (user) {
          navigate("/");
        }
      }
    } catch (e) {
      console.log("Err", e.message);
    }
  };

  return (
    <div className="wrapper row">
      <div className="wrapper-left">
        <img src={loginImg} />
        <h3 className="primary-text">
          WELCOME TO <span>GREENHUB</span>
        </h3>
        <p>
          Our eco-friendly digital haven, where sustainable living meets
          effortless shopping!
        </p>
      </div>
      <div className="wrapper-right">
        <form onSubmit={onSubmitHandler}>
          <label>
            <p>Your Email</p>
            <input
              type="email"
              id="username"
              name="username"
              value={userMail}
              onChange={(e) => setUserMail(e.target.value)}
              required
            />
          </label>
          <label>
            <p>Password</p>
            <input
              type="password"
              className="input-password"
              id="password"
              name="password"
              value={userPassword}
              onChange={(e) => setUserPassword(e.target.value)}
              required
            />
          </label>
          <button type="submit" className="btn-login">
            Login
          </button>
        </form>
      </div>
    </div>
  );
};

export default Login;

// frontend/src/app/components/login/login.component.ts
import { CommonModule } from '@angular/common';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule, HttpClientModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss',
})
export class LoginComponent {
  // constructor(private authService: AuthService) {}

  // login(username: string, password: string) {
  //   this.authService.login(username, password).subscribe((success) => {
  //     if (success) {
  //       // login successful, navigate to another page or show success message
  //       console.log("success")
  //     } else {
  //       // login failed, show error message
  //       console.log("fkd")
  //     }
  //   });
  // }

  loginObj: Login;
  constructor(private http: HttpClient) {
    this.loginObj = new Login();
  }

  onLogin() {
    console.log('uname', this.loginObj.username, 'pw', this.loginObj.password);
    // Check if both username and password are provided
    if (!this.loginObj.username || !this.loginObj.password) {
      console.error('Username and password are required.');
      return;
    }

    this.http
      .post('http://localhost:8000/v1/login/', this.loginObj)
      .subscribe((res: any) => {
        if (res.result) {
          console.log('Login Success');
        } else {
          console.log(res.message);
        }
      });
  }
}

export class Login {
  username: string;
  password: string;
  constructor() {
    this.username = '';
    this.password = '';
  }
}

<div class="wrapper row">
  <div class="wrapper-left">
    <img src="assets/images/bgs/login.png" />
    <h3 class="primary-text">WELCOME TO <span>GREENHUB</span></h3>
    <p>
      Our eco-friendly digital haven, where sustainable living meets effortless
      shopping!
    </p>
  </div>
  <div class="wrapper-right">
    <form>
      <label>
        <p>Your Email</p>
        <input
          type="email"
          #username
          [(ngModel)]="loginObj.username"
          name="username"
          required
        />
      </label>
      <label>
        <p>Password</p>
        <input
          type="password"
          class="input-password"
          #password
          [(ngModel)]="loginObj.password"
          name="password"
          required
        />
      </label>
      <button type="button" class="btn-login" (click)="onLogin()">Login</button>
    </form>
  </div>
</div>

<!-- [(ngModel)]="loginObj.username"
          name="username"
          required -->
<!-- [(ngModel)]="loginObj.password"
          name="password"
          required -->
<!-- (click)="onLogin() -->
